import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import CustomCanvas from "../components/Canvas";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
        <h1 className="text-2xl font-bold">Hello world</h1>
        <CustomCanvas />
      </div>
    </>
  );
};

export default Home;
