import Head from "next/head";

interface IProps {
  children: JSX.Element;
}

export default function SiteWrapper(props: IProps) {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-darkred-500 text-white">
        {/* <Navbar/> */}
        <main className="w-screen min-h-screen h-full">{props.children}</main>
        {/* <Footer/> */}
      </div>
    </>
  );
}
