import type { NextPage } from 'next';
import Head from 'next/head';

const AddBlogForm: NextPage = () => {
  return (
    <div className='bg-oxford-500 h-screen'>
      <Head>
        <title>cuvar | Add Blog</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main className='flex items-center flex-col text-beigewhite-500 '>
        <div className='mb-5 w-1/2 flex flex-col mt-20'>
          <h1 className='font-bold text-2xl mb-2 text-byzantium-500'>
            Adding a new post
          </h1>
          <label htmlFor='' className='mr-2'>
            File name
          </label>
          <input
            type='text'
            id='blog-add-name'
            className='w-full mb-4 p-2 text-black rounded-md focus:outline-none focus:ring focus:border-crayola-200-500'
          />
          <label htmlFor='' className='mr-2 truncate'>
            Blog content
          </label>
          <textarea
            name='hello'
            id='blog-add-content'
            className='resize-none mb-4 w-full h-48 p-2 text-black rounded-md focus:outline-none focus:ring focus:border-crayola-200-500'></textarea>
          <button
            onClick={() => addBlogPost()}
            className='bg-crayola-200-500 text-black rounded-lg py-2 px-4 hover:bg-crayola-200-500'>
            Send
          </button>
        </div>
      </main>
    </div>
  );
};

function addBlogPost() {
  // blog-add-content
  // blog-add-name
}

export default AddBlogForm;
