import type { NextPage } from 'next';
import Head from 'next/head';

const About: NextPage = () => {
  return (
    <div className='bg-oxford-500 h-screen'>
      <Head>
        <title>cuvar | About</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main className='h-screen flex justify-center items-center'>
        <h1 className='my-auto text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-byzantium-500 to-crayola-500'>
          This part of the website is currently under construction.
        </h1>
      </main>
    </div>
  );
};

export default About;
