name: Deploy to server

on:
  push:
    # branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.2
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Create build output
        run: |
          npm install
          npm run build
          cd ..
      - name: Copy to production via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTN }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATEKEY }}
          source: client/build
          target: content
          debug: true
          rm: true
